server:
  port: 8189
  servlet:
    context-path: /security
#    session:
#      timeout: 60s
spting:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
#        dialect: org.hibernate.dialect.H2Dialect
#        ddl-auto: none
#        temp:
#          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=springsecurity
    username: postgres
    password: 123
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
